### ISSUE TITLE
9월 28일 / Java 코딩테스트 연습 (jaeyeon)

### ISSUE THREAD

**Issue by jaeyyyyy** [enoch012/JavaBasicStudy#3]
# 문제 1

## 문제
- [문제링크] (https://school.programmers.co.kr/learn/courses/30/lessons/181949)
- 영어 알파벳으로 이루어진 문자열 str이 주어집니다. 각 알파벳을 대문자는 소문자로 소문자는 대문자로 변환해서 출력하는 코드를 작성해 보세요.
- 제한사항
> 1 ≤ str의 길이 ≤ 20
str은 알파벳으로 이루어진 문자열입니다.

## 입출력 예
- 입력
> aBcDeFg

- 출력
> AbCdEfG

## 문제풀이
 1. 아스키코드를 사용함
 2. 1을 위해 `char`형 배열로 바꿈
 
> 아스키 코드에서 대소문자 간에 번호가 32만큼 차이가 납니다.
 대문자로 바꿀 때는 -32를 소문자로 바꿀 때는 +32를 할 것임

```java
char lower1 = 'a'; // 문자로 표현
char lower2 = 97; // 아스키 코드로 표현
char upper1 = 'A';
char upper2 = 65;
```

```java
import java.util.Scanner;

public class Solution {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        String a = sc.next();
        char[] arr = a.toCharArray();
        
           for (int i = 0; i < arr.length; i++) {
                if (arr[i] >= 'a' && arr[i] <= 'z') {
                    arr[i] = (char)(arr[i]-32);
                    continue;
                    }
                if (arr[i] >= 'A' && arr[i] <= 'Z') {
                    arr[i] = (char)(arr[i]+32);
                    continue;
                    }
            }
            System.out.println(arr);
    }
}
```

## 회고
- 제한사항 조건을 추가해야한다.
- toUpperCase, toLowerCase 메소드를 사용하면 더 간략하게 작성할 수 있다.
- char 필요함

```java
import java.util.Scanner;

public class Solution {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        String a = sc.next();
        String answer = "";

        for(int i = 0; i< a.length(); i++){
            char c = a.charAt(i);
            if(Character.isUpperCase(c)){
                answer += Character.toLowerCase(c);
            } else{
                answer += Character.toUpperCase(c);
            }
        }
        System.out.println(answer);
    }
}
```

- isUpperCase 메소드로 대문자인지 확인하고 아스키코드를 사용하여 대소문자를 변환한 코드

```java
import java.util.Scanner;

public class Solution {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        String a = sc.next();
        String answer = "";
        for(int i = 0; i< a.length(); i++){
            char c = a.charAt(i);
            if(Character.isUpperCase(c)){
                answer += ((char)(c+32));
            } else{
                answer += ((char)(c-32));
            }
        }
        System.out.println(answer);
    }
} 
```

**Comment by jaeyyyyy** [comment]
# 문제 2

## 문제
- [문제링크] (https://school.programmers.co.kr/learn/courses/30/lessons/181943)
- 문자열 `my_string`, `overwrite_string`과 정수 `s`가 주어집니다. 문자열 `my_string`의 인덱스 `s`부터 `overwrite_string`의 길이만큼을 문자열 `overwrite_string`으로 바꾼 문자열을 return 하는 solution 함수를 작성해 주세요.
- 제한사항
 > `my_string`와 `overwrite_string`은 숫자와 알파벳으로 이루어져 있습니다.
1 ≤ `overwrite_string`의 길이 ≤ `my_string`의 길이 ≤ 1,000
0 ≤ `s` ≤ `my_string`의 길이 - `overwrite_string`의 길이

## 입출력 예
my_string | overwrite_string | s | result
-- | -- | -- | --
"He11oWor1d" | "lloWorl" | 2 | "HelloWorld"
"Program29b8UYP" | "merS123" | 7 | "ProgrammerS123"

- 입출력 예 1
> 예제 1번의 `my_string`에서 인덱스 2부터 `overwrite_string`의 길이만큼에 해당하는 부분은 "11oWor1"이고 이를 "lloWorl"로 바꾼 "HelloWorld"를 return 합니다.

- 입출력 예 2
> 예제 2번의 `my_string`에서 인덱스 7부터 `overwrite_string`의 길이만큼에 해당하는 부분은 "29b8UYP"이고 이를 "merS123"로 바꾼 "ProgrammerS123"를 return 합니다.

## 문제풀이
- substring을 사용하여 문자열을 필요한 만큼 잘랐다.

```java
class Solution {
    public String solution(String my_string, String overwrite_string, int s) {
        int l = my_string.length();
        int l2 = overwrite_string.length();
        
        String answer = my_string.substring(0, s) + overwrite_string;
        if (my_string.length() > answer.length()) {
            answer += my_string.substring(l2+s, l);
        }
        return answer;
    }
}
```

## 회고
- 제한사항 조건을 추가해야된다.
- if 문 생략하고 이렇게 작성하는 것이 더 깔끔하다.
```java
class Solution {
    public String solution(String my_string, String overwrite_string, int s) {
        int l = my_string.length();
        int l2 = overwrite_string.length();
        
        String answer = my_string.substring(0, s) + overwrite_string + my_string.substring(s + l2);
        
        return answer;
        }
    }
```

**Comment by jaeyyyyy** [comment]
# 문제 3
## 문제
- [문제링크] (https://school.programmers.co.kr/learn/courses/30/lessons/181932)
- 문자열 `code`가 주어집니다.
`code`를 앞에서부터 읽으면서 만약 문자가 "1"이면 `mode`를 바꿉니다. `mode`에 따라 `code`를 읽어가면서 문자열 `ret`을 만들어냅니다.
`mode`는 0과 1이 있으며, `idx`를 0 부터 `code의 길이 - 1` 까지 1씩 키워나가면서 `code[idx]`의 값에 따라 다음과 같이 행동합니다.
- `mode`가 0일 때
`code[idx]`가 "1"이 아니면 `idx`가 짝수일 때만 `ret`의 맨 뒤에 `code[idx]`를 추가합니다.
`code[idx]`가 "1"이면 `mode`를 0에서 1로 바꿉니다.
- `mode`가 1일 때
`code[idx]`가 "1"이 아니면 `idx`가 홀수일 때만 `ret`의 맨 뒤에 `code[idx]`를 추가합니다.
`code[idx]`가 "1"이면 `mode`를 1에서 0으로 바꿉니다.
- 문자열 `code`를 통해 만들어진 문자열 `ret`를 return 하는 solution 함수를 완성해 주세요.
단, 시작할 때 `mode`는 0이며, return 하려는 `ret`가 만약 빈 문자열이라면 대신 "EMPTY"를 return 합니다.

- 제한사항
1 ≤ code의 길이 ≤ 100,000
code는 알파벳 소문자 또는 "1"로 이루어진 문자열입니다.

## 입출력 예

code | result
-- | --
"abc1abc1abc" | "acbac"



- 입출력 예 1

`code`의 각 인덱스 `i`에 따라 다음과 같이 `mode`와 `ret`가 변합니다.

i | code[i] | mode | ret
-- | -- | -- | --
0 | "a" | 0 | "a"
1 | "b" | 0 | "a"
2 | "c" | 0 | "ac"
3 | "1" | 1 | "ac"
4 | "a" | 1 | "ac"
5 | "b" | 1 | "acb"
6 | "c" | 1 | "acb"
7 | "1" | 0 | "acb"
8 | "a" | 0 | "acba"
9 | "b" | 0 | "acba"
10 | "c" | 0 | "acbac"

따라서 "acbac"를 return 합니다.

## 문제풀이
- charAt을 사용하여 code를 하나씩 잘랐다.
- 모드가 0인지 1인지부터 먼저 나눈 다음에 문제 순서대로 그대로 적었음

```java
class Solution {
    public String solution(String code) {
        String answer = "";
        int mode = 0;
        
        for (int i = 0; i < code.length(); i++) {
            char a = code.charAt(i);
        
            if (mode == 0) {
                if (a != '1') {
                    if (i % 2 == 0) {
                    answer += a;
                    }
                } else {
                    mode = 1;
                }

            } else if (mode == 1) {
                if (a != '1') {
                    if (i % 2 != 0) {
                    answer += a;
                    }
                } else {
                    mode = 0;
                }
            } 
        }
        if (answer.equals("")) {
            answer = "EMPTY";
        }
        
        return answer;
    }
}
```
## 회고
- 제한사항 조건을 추가해야된다.
- if문을 여러 번 사용했고, 중복되는 부분도 있다. 코드가 길어지고 복잡하다.
- 간결하게 쓰려고 삼항연산자를 사용했다.
- 다른 사람의 풀이를 참고하여 아래의 코드를 작성했다.

> mode 가 1일 때, a가 1이 아니면 i가 홀수일 경우에 `answer += a;`를 하는데 mode 가 0일 때, a가 1이 아니면 i가 짝수일 경우에 똑같이  `answer += a;`를 한다.
이것을 아래처럼 작성하면 mode가 1이면 i는 무조건 홀수가 되고, mode가 0이면 i는 무조건 짝수가 된다.
```java
           if (a != '1') {
              if (i % 2 == mode) {
                answer += a;
              }
           }
```

```java
class Solution {
    public String solution(String code) {
        String answer = "";
        int mode = 0;
        
        for (int i = 0; i < code.length(); i++) {
            char a = code.charAt(i);
        
           if (a != '1') {
              if (i % 2 == mode) {
                answer += a;
              }
           }
           if (a == '1') {
               mode = mode == 0 ? 1 : 0;
               }
           }
            
        return answer.equals("") ? "EMPTY" : answer;
    }
}
```

**Comment by SDeung01** [comment]
다른 사람의 코드를 참고에 그치지 않고 학습한 것을 토대로 본래의 코드를 적절하게 리팩토링하는 방식이 많은 참고가 되었습니다.

변수를 선언할때 변수명이 간결하여 어떤 기능을 하는 변수인지 짐작이 어려운 부분이 조금 보이는 것 같습니다. 변수명이 의미를 가지도록 짓거나 주석으로 어떤 기능을 하는지 덧붙여 설명을 한다면 지금보다 더 가독성있는 코드가 될 것 같습니다.

**Comment by enoch012** [comment]
- 다른 사람의 코드를 참고하여 리팩토링 한 부분이 마찬가지로 좋았다고 생각합니다 👍
- 어떤 기능을 하는 함수인지, 어떤 의미를 가진 변수인지 간단하게 주석으로 남기는 연습도 추가해보면 좋을 거 같습니다! 결국 다른 사람과 서로 코드를 공유하게 되어있으니까요 :3 고생하셨습니다 💪
